# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);


POST http://codex.local/_git-webhook/github
User-Agent: GitHub-Hookshot/86b2a17
X-GitHub-Delivery: fd9021a0-678a-11e9-9148-112d50a7e800
X-GitHub-Event: ping
Content-Type: application/json

{
  "zen": "It's not fully shipped until it's fast.",
  "hook_id": 104914253,
  "hook": {
    "type": "Organization",
    "id": 104914253,
    "name": "web",
    "active": true,
    "events": [
      "*"
    ],
    "config": {
      "content_type": "form",
      "insecure_ssl": "0",
      "url": "http://dev.radic.ninja/_git-webhook/github/"
    },
    "updated_at": "2019-04-25T18:50:26Z",
    "created_at": "2019-04-25T18:50:26Z",
    "url": "https://api.github.com/orgs/codex-project/hooks/104914253",
    "ping_url": "https://api.github.com/orgs/codex-project/hooks/104914253/pings"
  },
  "organization": {
    "login": "codex-project",
    "id": 9723346,
    "node_id": "MDEyOk9yZ2FuaXphdGlvbjk3MjMzNDY=",
    "url": "https://api.github.com/orgs/codex-project",
    "repos_url": "https://api.github.com/orgs/codex-project/repos",
    "events_url": "https://api.github.com/orgs/codex-project/events",
    "hooks_url": "https://api.github.com/orgs/codex-project/hooks",
    "issues_url": "https://api.github.com/orgs/codex-project/issues",
    "members_url": "https://api.github.com/orgs/codex-project/members{/member}",
    "public_members_url": "https://api.github.com/orgs/codex-project/public_members{/member}",
    "avatar_url": "https://avatars1.githubusercontent.com/u/9723346?v=4",
    "description": "Codex is a file-based documentation platform built on top of Laravel. It's completely customizable and dead simple to use to create beautiful documentation."
  },
  "sender": {
    "login": "RobinRadic",
    "id": 754732,
    "node_id": "MDQ6VXNlcjc1NDczMg==",
    "avatar_url": "https://avatars3.githubusercontent.com/u/754732?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/RobinRadic",
    "html_url": "https://github.com/RobinRadic",
    "followers_url": "https://api.github.com/users/RobinRadic/followers",
    "following_url": "https://api.github.com/users/RobinRadic/following{/other_user}",
    "gists_url": "https://api.github.com/users/RobinRadic/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/RobinRadic/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/RobinRadic/subscriptions",
    "organizations_url": "https://api.github.com/users/RobinRadic/orgs",
    "repos_url": "https://api.github.com/users/RobinRadic/repos",
    "events_url": "https://api.github.com/users/RobinRadic/events{/privacy}",
    "received_events_url": "https://api.github.com/users/RobinRadic/received_events",
    "type": "User",
    "site_admin": false
  }
}
###
