<?php

return [
    'header'    => [
        'color'             => 'blue-grey-9',
        'show'              => true,
        'show_left_toggle'  => true,
        'show_right_toggle' => false,
        'fixed'             => false,
        'class'             => [ 'c-layout-header' => true ],
        'style'             => [],
        'menu'              => [
            [
                'label'    => 'Projects',
                'sublabel' => '<%= store.project.display_name || "" %>',
                'projects' => true,
                'type'     => 'side-menu',
                'side'     => 'right',
                'icon'     => 'book',
                'renderer' => 'big',
            ],
            [
                'label'     => 'Revisions',
                'sublabel'  => '<%= store.revision.key || "" %>',
                'revisions' => true,
                'type'      => 'side-menu',
                'side'      => 'right',
                'icon'      => 'code-fork',
                'renderer'  => 'big',
            ],
        ],
        'height'            => 64,
        'children'          => null,
    ],
    'left'      => [
        'show'           => true,
        'collapsed'      => false,
        'outside'        => false,
        'collapsedWidth' => 50,
        'width'          => 250,
        'class'          => [ 'c-layout-left' => true ],
        'style'          => [],
        'menu'           => [],
        'children'       => null,
    ],
    'right'     => [
        'show'           => true,
        'collapsed'      => true,
        'outside'        => false,
        'collapsedWidth' => 0,
        'width'          => 250,
        'class'          => [ 'c-layout-right' => true ],
        'style'          => [],
        'menu'           => [],
        'children'       => null,
    ],
    'footer'    => [
        'show'     => true,
        'fixed'    => false,
        'height'   => 64,
        'color'    => 'blue-grey-9',
        'class'    => [ 'c-layout-footer' => true ],
        'style'    => [],
        'menu'     => [],
        'children' => null,
    ],
    'container' => [
        'class'    => [ 'c-layout-container' => true ],
        'style'    => [],
        'stretch'  => true,
        'children' => null,
    ],
    'middle'    => [
        'class'    => [ 'c-layout-middle' => true ],
        'style'    => [],
        'padding'  => 0,
        'margin'   => 0,
        'children' => null,
    ],
    'content'   => [
        'class'    => [ 'c-layout-content' => true ],
        'style'    => [],
        'color'    => 'grey-1',
        'padding'  => '12px 24px',
        'margin'   => 24,
        'children' => null,
    ],
    'toolbar'   => [
        'class'    => [ 'c-layout-toolbar' => true ],
        'style'    => [],
        'color'    => 'grey-1',
        'show'     => true,
        'fixed'    => true,
        'left'     => [
            [ 'component' => 'c-layout-breadcrumbs' ],
        ],
        'right'    => [],
        'children' => null,
    ],
];
